version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  win: circleci/windows@2.2.0

install_secman_windows: &install_secman_windows
  name: Install Secman (Windows)
  command: iwr -useb https://secman-team.github.io/install.ps1 | iex

jobs:
  node-latest: &test
    executor:
      name: win/default
      shell: powershell.exe

    working_directory: ~/cli
    steps:
      - checkout
      - run:
          <<: *install_secman_windows
          shell: powershell.exe

      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run: ./bin/run start
      - run:
          name: Testing
          command: npm test

  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "sm-upg":
    jobs:
      - node-latest
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
