name: Node.js CI

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: iwr -useb https://cli.secman.dev/install.ps1 | iex
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
